version: "3.9"

services:
  laravel_app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/var/www
      - /var/www/vendor # Evita que el volumen pise las dependencias instaladas en el build
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=IleApaindegi
      - APP_ENV=production
      - APP_KEY=base64:uS9vXG7z7OIn/1M3GqY8yXvL3pQ8YfV9WjK6LzM4N5E=
      - APP_DEBUG=false # En AWS mejor false para evitar fugas de info
      - APP_URL=http://98.85.48.192 # La IP pÃºblica del Backend
      
      # Base de Datos RDS
      - DB_CONNECTION=mysql
      - DB_HOST=ia-rds.ckh0gwvuxkn7.us-east-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_DATABASE=ile_apaindegi
      - DB_USERNAME=santurtziTesting
      - DB_PASSWORD=A2fKhg:Y)7ln7mN_p{\FW
    command: >
      sh -c "composer install --no-interaction --optimize-autoloader &&
             php artisan config:cache &&
             php artisan route:cache &&
             php artisan migrate --force &&
             php artisan serve --host=0.0.0.0 --port=8000"